export const BACK_MAIN_PAGE_REQUEST = "BACK_MAIN_PAGE_REQUEST"
export const BACK_MAIN_PAGE_SUCCESS = "BACK_MAIN_PAGE_SUCCESS"
export const BACK_MAIN_PAGE_FAIL = "BACK_MAIN_PAGE_FAIL"
export const BACK_MAIN_PAGE_RESET = "BACK_MAIN_PAGE_RESET"

