export const CONVERSATION_STYLE_REQUEST = "CONVERSATION_STYLE_REQUEST"
export const CONVERSATION_STYLE_SUCCESS = "CONVERSATION_STYLE_SUCCESS"
export const CONVERSATION_STYLE_FAIL = "CONVERSATION_STYLE_FAIL"
export const CONVERSATION_STYLE_RESET = "CONVERSATION_STYLE_RESET"