export const NEW_CRITIQUED_PRODUCT_REQUEST = "NEW_CRITIQUED_PRODUCT_REQUEST"
export const NEW_CRITIQUED_PRODUCT_SUCCESS = "NEW_CRITIQUED_PRODUCT_SUCCESS"
export const NEW_CRITIQUED_PRODUCT_FAIL = "NEW_CRITIQUED_PRODUCT_FAIL"
export const NEW_CRITIQUED_PRODUCT_RESET = "NEW_CRITIQUED_PRODUCT_RESET"