

export const ALL_FILTER_STATE_REQUEST = "ALL_FILTER_STATE_REQUEST"
export const ALL_FILTER_STATE_SUCCESS = "ALL_FILTER_STATE_SUCCESS"
export const ALL_FILTER_STATE_FAIL = "ALL_FILTER_STATE_FAIL"
export const ALL_FILTER_STATE_RESET = "ALL_FILTER_STATE_RESET"


export const ONE_FILTER_TOTAL_VALUE_REQUEST = "ONE_FILTER_TOTAL_VALUE_REQUEST"
export const ONE_FILTER_TOTAL_VALUE_SUCCESS = "ONE_FILTER_TOTAL_VALUE_SUCCESS"
export const ONE_FILTER_TOTAL_VALUE_FAIL = "ONE_FILTER_TOTAL_VALUE_FAIL"
export const ONE_FILTER_TOTAL_VALUE_RESET = "ONE_FILTER_TOTAL_VALUE_RESET"


export const ALL_FILTER_TOTAL_VALUE_REQUEST = "ALL_FILTER_TOTAL_VALUE_REQUEST"
export const ALL_FILTER_TOTAL_VALUE_SUCCESS = "ALL_FILTER_TOTAL_VALUE_SUCCESS"
export const ALL_FILTER_TOTAL_VALUE_FAIL = "ALL_FILTER_TOTAL_VALUE_FAIL"
export const ALL_FILTER_TOTAL_VALUE_RESET = "ALL_FILTER_TOTAL_VALUE_RESET"


export const INITIAL_ALL_FILTER_TOTAL_VALUE_SUCCESS = "INITIAL_ALL_FILTER_TOTAL_VALUE_SUCCESS"
export const INITIAL_ALL_FILTER_TOTAL_VALUE_FAIL = "INITIAL_ALL_FILTER_TOTAL_VALUE_FAIL"