export const FIRST_RANK_FEATURE_REQUEST = "FIRST_RANK_FEATURE_REQUEST"
export const FIRST_RANK_FEATURE_SUCCESS = "FIRST_RANK_FEATURE_SUCCESS"
export const FIRST_RANK_FEATURE_FAIL = "FIRST_RANK_FEATURE_FAIL"
export const FIRST_RANK_FEATURE_RESET = "FIRST_RANK_FEATURE_RESET"