export const IN_MAIN_PAGE_REQUEST = "IN_MAIN_PAGE_REQUEST"
export const IN_MAIN_PAGE_SUCCESS = "IN_MAIN_PAGE_SUCCESS"
export const IN_MAIN_PAGE_FAIL = "IN_MAIN_PAGE_FAIL"
export const IN_MAIN_PAGE_RESET = "IN_MAIN_PAGE_RESET"

