export const INTERACTION_TRACK_REQUEST = "INTERACTION_TRACK_REQUEST"
export const INTERACTION_TRACK_SUCCESS = "INTERACTION_TRACK_SUCCESS"
export const INTERACTION_TRACK_FAIL = "INTERACTION_TRACK_FAIL"
export const INTERACTION_TRACK_RESET = "INTERACTION_TRACK_RESET"