export const META_INTENTS_PROFILE_REQUEST = "META_INTENTS_PROFILE_REQUEST"
export const META_INTENTS_PROFILE_SUCCESS = "META_INTENTS_PROFILE_SUCCESS"
export const META_INTENTS_PROFILE_FAIL = "META_INTENTS_PROFILE_FAIL"
export const META_INTENTS_PROFILE_RESET = "META_INTENTS_PROFILE_RESET"