export const USER_INDEX_REQUEST = "USER_INDEX_REQUEST"
export const USER_INDEX_SUCCESS = "USER_INDEX_SUCCESS"
export const USER_INDEX_FAIL = "USER_INDEX_FAIL"
export const USER_INDEX_RESET = "USER_INDEX_RESET"

export const USER_RG01_REQUEST = "USER_RG01_REQUEST"
export const USER_RG01_SUCCESS = "USER_RG01_SUCCESS"
export const USER_RG01_FAIL = "USER_RG01_FAIL"
export const USER_RG01_RESET = "USER_RG01_RESET"


